In [7]:
#part 4 p-1
# Coefficient matrix A (3x3)
A1 = np.array([
    [2, 1, -1],
    [-1, 3, 2],
    [1, -2, 4]
])

# Constant matrix B (3x1)
B1 = np.array([5, 6, 7])

# Check if matrix A1 is invertible (determinant should not be zero)
det_A1 = np.linalg.det(A1)
if det_A1 == 0:
    print("Matrix A1 is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A1
    A1_inv = np.linalg.inv(A1)

    # Solve for X using the matrix inverse method
    X1 = np.dot(A1_inv, B1)

    # Output the solution (the values of x1, x2, x3)
    print("Solution for Problem 1 (Unknowns):")
    print(X1)


Solution for Problem 1 (Unknowns):
[2.64102564 1.61538462 1.8974359 ]


In [10]:
#part 4 p-2
# Coefficient matrix A (5x5)
A2 = np.array([
    [5, 3, 1, 1, 0],
    [4, 6, 2, 0, 1],
    [2, 7, 3, 1, 0],
    [1, 2, 4, 5, 0],
    [3, 4, 5, 0, 6]
])

# Constant matrix B (5x1)
B2 = np.array([200, 300, 150, 120, 250])

# Check if matrix A2 is invertible (determinant should not be zero)
det_A2 = np.linalg.det(A2)
if det_A2 == 0:
    print("Matrix A2 is singular and cannot be inverted!")
else:
    # Find the inverse of matrix A2
    A2_inv = np.linalg.inv(A2)

    # Solve for X using the matrix inverse method
    X2 = np.dot(A2_inv, B2)

    # Output the solution (the values of x1, x2, x3, x4, x5)
    print("Solution for Problem 2 (Unknowns):")
    print(X2)


Solution for Problem 2 (Unknowns):
[ -23.86666667  137.6        -336.          242.53333333  241.86666667]


In [15]:
#part 4 p-3
# Coefficient matrix A (7x7)
A3 = np.random.rand(7, 7)

# Constant matrix B (7x1)
B3 = np.random.rand(7)

# Check if matrix A3 is invertible (determinant should not be zero)
det_A3 = np.linalg.det(A3)
if det_A3 == 0:
    print("Matrix A3 is singular so it cannot be inverted!")
else:
    # Find the inverse of matrix A3
    A3_inv = np.linalg.inv(A3)

    # Solve for X using the matrix inverse method
    X3 = np.dot(A3_inv, B3)

    # Output the solution (the values of x1, x2, ..., x7)
    print("Unknowns:")
    print(X3)


Unknowns:
[-6.35979374  0.64317486  1.91586266  0.17992165  5.79699282  1.7858864
 -1.69121153]


In [22]:
def solve_random_linear_system():
    # Generate a random 5x5
    A = np.random.rand(5, 5)

    # Generate a random 5x1
    B = np.random.rand(5)

    # Check if matrix A is invertible (determinant should not be zero)
    det_A = np.linalg.det(A)
    if det_A == 0:
        print("Matrix A is singular and cannot be inverted!")
        return None
    else:
        # Find the inverse of matrix A
        A_inv = np.linalg.inv(A)

        # Solve for X using the matrix inverse method
        X = np.dot(A_inv, B)

        print("Solution for Problem 4 (Unknowns):")
        print(X)

# Example usage
solve_random_linear_system()

Solution for Problem 4 (Unknowns):
[-0.54144548  0.79433348  0.29588905  0.25379537 -0.12051591]


In [21]:
#part 4 p-5
def solve_linear_system(A, B):
    # Check if matrix A is invertible (determinant should not be zero)
    det_A = np.linalg.det(A)
    if det_A == 0:
        print("Matrix A is singular and cannot be inverted!")
        return None
    else:
        # Find the inverse of matrix A
        A_inv = np.linalg.inv(A)

        # Solve for X using the matrix inverse method
        X = np.dot(A_inv, B)

        # Output the solution (the values of the unknowns)
        print("Solution (Unknowns):")
        print(X)


A1 = np.array([
    [2, 1, -1],
    [-1, 3, 2],
    [1, -2, 4]
])
B1 = np.array([5, 6, 7])
solve_linear_system(A1, B1)


Solution (Unknowns):
[2.64102564 1.61538462 1.8974359 ]


array([2.64102564, 1.61538462, 1.8974359 ])