In [ ]:
import numpy as np

# Step 1: Define the given 3x4 matrix
matrix_3x4 = np.array([
    [12, 16, 9, 1],
    [15, 16, 8, 13],
    [11, 4, 9, 5]
])

# Extract the coefficient matrix (A) and the right-hand side vector (b)
A = matrix_3x4[:, :3]  # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3]   # Right-hand side vector (last column)

# Display the matrix, A, and b
print("Given 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

# Solve using Gaussian Elimination
try:
    x_gaussian = np.linalg.solve(A, b)
    print("\nSolution using Gaussian Elimination (NumPy):")
    print(x_gaussian)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular or not solvable.")

# Verify the solution
try:
    b_check = np.dot(A, x_gaussian)
    print("\nVerification (Ax = b):")
    print(b_check)
except:
    print("\nVerification could not be performed.")


Given 3x4 Matrix:
[[12 16  9  1]
 [15 16  8 13]
 [11  4  9  5]]

Coefficient Matrix (A):
[[12 16  9]
 [15 16  8]
 [11  4  9]]

Right-hand Side Vector (b):
[ 1 13  5]

Solution using Matrix Inverse Method:
[ 3.03539823 -0.58628319 -2.89380531]

Solution using Gaussian Elimination (NumPy):
[ 3.03539823 -0.58628319 -2.89380531]

Verification (Ax = b):
[ 1. 13.  5.]
