1.Use Naïve Gauss elimination to solve

In [2]:
import numpy as np

# Step 1: Define the augmented matrix for the system
A = np.array([
    [4, 1, -1, -2],
    [5, 1, 2, 4],
    [6, 1, 1, 6]
], dtype=float)

# Function to perform Naïve Gauss Elimination
def gauss_elimination(A):
    n = len(A)

    # Forward Elimination
    for i in range(n-1):
        for j in range(i+1, n):
            if A[i][i] == 0:
                raise ValueError("Mathematical Error: Division by zero detected!")
            factor = A[j][i] / A[i][i]
            for k in range(n+1):
                A[j][k] -= factor * A[i][k]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = A[i][-1]
        for j in range(i+1, n):
            x[i] -= A[i][j] * x[j]
        x[i] /= A[i][i]

    return x

# Solve the system
solution = gauss_elimination(A)
solution


array([  3., -13.,   1.])

2. Assume that you are using a computer with four significant digits with chopping.
Use Naïve Gauss elimination method to solve

In [3]:
# Reinitialize the augmented matrix with 4 significant digits
A = np.array([
    [4, 1, -1, -2],
    [5, 1, 2, 4],
    [6, 1, 1, 6]
], dtype=float)

def gauss_elimination_chop(A, significant_digits=4):
    n = len(A)

    # Function to chop numbers to significant digits
    chop = lambda x: float(f"{x:.{significant_digits}g}")

    # Forward Elimination
    for i in range(n-1):
        for j in range(i+1, n):
            if A[i][i] == 0:
                raise ValueError("Mathematical Error: Division by zero detected!")
            factor = chop(A[j][i] / A[i][i])
            for k in range(n+1):
                A[j][k] = chop(A[j][k] - chop(factor * A[i][k]))

    # Back Substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = chop(A[i][-1])
        for j in range(i+1, n):
            x[i] = chop(x[i] - chop(A[i][j] * x[j]))
        x[i] = chop(x[i] / A[i][i])

    return x

# Solve the system with 4 significant digits and chopping
solution_chopped = gauss_elimination_chop(A)
solution_chopped


array([  3., -13.,   1.])

3. Find the determinant of [A] using forward elimination step of naïve Gauss
elimination method.

In [4]:
# Define the matrix A
A = np.array([
    [10, -7, 0],
    [-3, 2.099, 6],
    [5, -1, 5]
], dtype=float)

def determinant_via_gauss_elimination(A):
    n = len(A)
    det = 1
    for i in range(n):
        # If diagonal element is zero, determinant is zero
        if A[i][i] == 0:
            return 0
        for j in range(i+1, n):
            factor = A[j][i] / A[i][i]
            A[j] = A[j] - factor * A[i]
        det *= A[i][i]  # Multiply diagonal element to determinant

    return det

# Calculate the determinant
determinant = determinant_via_gauss_elimination(A)
determinant


-150.04999999999998

In [ ]:
# Diagonal elements of the upper triangular matrix
diag_elements = [25, -4.8, 0.7]

# Compute the determinant as the product of diagonal elements
determinant = np.prod(diag_elements)
determinant


5. Using Gaussian elimination with partial pivoting to solve

In [5]:
# Reinitialize the augmented matrix
A = np.array([
    [4, 1, -1, -2],
    [5, 1, 2, 4],
    [6, 1, 1, 6]
], dtype=float)

def gauss_elimination_partial_pivoting(A):
    n = len(A)

    # Forward elimination with partial pivoting
    for i in range(n):
        # Partial Pivoting: Find the maximum element in the current column
        max_row = np.argmax(np.abs(A[i:n, i])) + i
        if i != max_row:
            A[[i, max_row]] = A[[max_row, i]]  # Swap rows

        for j in range(i+1, n):
            factor = A[j][i] / A[i][i]
            A[j] = A[j] - factor * A[i]

    # Back Substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = A[i][-1]
        for j in range(i+1, n):
            x[i] -= A[i][j] * x[j]
        x[i] /= A[i][i]

    return x

# Solve the system using Gaussian elimination with partial pivoting
solution_pivoting = gauss_elimination_partial_pivoting(A)
solution_pivoting


array([  3., -13.,   1.])

6. Assume that you are using a computer with four significant digits with chopping,
use Gaussian elimination with partial pivoting to solve

In [6]:
# Redefine the augmented matrix A
A = np.array([
    [4, 1, -1, -2],
    [5, 1, 2, 4],
    [6, 1, 1, 6]
], dtype=float)

def gauss_elimination_partial_pivoting_chop(A, significant_digits=4):
    n = len(A)
    chop = lambda x: float(f"{x:.{significant_digits}g}")  # Function to chop numbers

    # Forward elimination with partial pivoting
    for i in range(n):
        # Partial Pivoting
        max_row = np.argmax(np.abs(A[i:n, i])) + i
        if i != max_row:
            A[[i, max_row]] = A[[max_row, i]]  # Swap rows

        # Chop after swapping
        A = np.vectorize(chop)(A)

        for j in range(i+1, n):
            factor = chop(A[j][i] / A[i][i])
            for k in range(i, n+1):
                A[j][k] = chop(A[j][k] - chop(factor * A[i][k]))

    # Back Substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = chop(A[i][-1])
        for j in range(i+1, n):
            x[i] = chop(x[i] - chop(A[i][j] * x[j]))
        x[i] = chop(x[i] / A[i][i])

    return x

# Solve the system with partial pivoting and chopping
solution_pivoting_chop = gauss_elimination_partial_pivoting_chop(A)
solution_pivoting_chop


array([  3., -13.,   1.])