In [1]:
import numpy as np

In [2]:
# Create a 2x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix A:")
print(A)

Matrix A:
[[1 2 3]
 [4 5 6]]


In [3]:
# 3x3 Zero Matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:")
print(zero_matrix)

# 3x3 Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:")
print(identity_matrix)

Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Define two matrices of the same shape
B = np.array([[1, 2], [3, 4]])
C = np.array([[5, 6], [7, 8]])

# Matrix Addition
addition_result = B + C
print("B + C:")
print(addition_result)

# Matrix Subtraction
subtraction_result = B - C
print("B - C:")
print(subtraction_result)

B + C:
[[ 6  8]
 [10 12]]
B - C:
[[-4 -4]
 [-4 -4]]


In [ ]:
#Excercise 1

# Defining two 3x3 matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Performing addition and subtraction
addition_result = matrix_a + matrix_b
subtraction_result = matrix_a - matrix_b

# Displaying the results
addition_result, subtraction_result

(array([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]),
 array([[-8, -6, -4],
        [-2,  0,  2],
        [ 4,  6,  8]]))

In [7]:
# Define matrices for multiplication
D = np.array([[1, 2], [3, 4]])
E = np.array([[2, 0], [1, 2]])

# Matrix Multiplication
multiplication_result = np.dot(D, E)
print("D * E (Matrix Multiplication):")
print(multiplication_result)

D * E (Matrix Multiplication):
[[ 4  4]
 [10  8]]


In [ ]:
#Excercise 2

# Defining a 2x3 matrix and a 3x2 matrix for multiplication
matrix_c = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
matrix_d = np.array([[7, 8], [9, 10], [11, 12]])  # 3x2 matrix

# Performing matrix multiplication
multiplication_result = np.dot(matrix_c, matrix_d)

# Displaying the result
multiplication_result

array([[ 58,  64],
       [139, 154]])

In [9]:
# Element-wise Multiplication
elementwise_result = D * E
print("D * E (Element-wise Multiplication):")
print(elementwise_result)

D * E (Element-wise Multiplication):
[[2 0]
 [3 8]]


In [12]:
#Excercise 3

# Creating a 2x3 matrix
matrix_e = np.array([[5, 7, 9], [2, 4, 6]])

# Finding the transpose of the matrix
transpose_matrix_e = np.transpose(matrix_e)

# Displaying the original and transposed matrices
matrix_e, transpose_matrix_e

(array([[5, 7, 9],
        [2, 4, 6]]),
 array([[5, 2],
        [7, 4],
        [9, 6]]))

In [13]:
# Define a 2x2 square matrix
F = np.array([[4, 2], [3, 1]])

# Determinant of F
determinant_result = np.linalg.det(F)
print("Determinant of F:", determinant_result)

Determinant of F: -2.0


In [ ]:
#Excercise 4

# Creating a 3x3 matrix
matrix_f = np.array([[3, 8, 4], [2, 5, 7], [6, 1, 9]])

# Calculating the determinant of the matrix
determinant_matrix_f = np.linalg.det(matrix_f)

# Displaying the determinant
determinant_matrix_f

194.00000000000003

In [16]:
# Define an invertible 2x2 matrix
G = np.array([[4, 7], [2, 6]])

# Inverse of G
inverse_result = np.linalg.inv(G)
print("Inverse of G:")
print(inverse_result)

Inverse of G:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [17]:
#Ecercise 5

# Creating an invertible 2x2 matrix
matrix_g = np.array([[4, 7], [2, 6]])

# Calculating the inverse of the matrix
inverse_matrix_g = np.linalg.inv(matrix_g)

# Displaying the inverse
inverse_matrix_g

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [18]:
# Generate a random 10x10 matrix
random_matrix_A = np.random.rand(10, 10)
print("Random 10x10 Matrix A:")
print(random_matrix_A)


Random 10x10 Matrix A:
[[0.16473724 0.47909095 0.74200837 0.25485524 0.19285782 0.4677832
  0.10349667 0.05606216 0.3879972  0.56635452]
 [0.87265118 0.92100396 0.10063558 0.58357116 0.97537555 0.12750453
  0.6340491  0.91450507 0.94894154 0.59076357]
 [0.66529098 0.48963655 0.14706056 0.43856323 0.10065697 0.62673385
  0.08053164 0.50527499 0.08461131 0.41832202]
 [0.68303657 0.37229699 0.47275049 0.30019481 0.5237802  0.34916938
  0.69341173 0.52589523 0.17616192 0.29636979]
 [0.14269761 0.21675181 0.1686948  0.96658397 0.98462893 0.20516593
  0.59605261 0.0044587  0.44745584 0.43592138]
 [0.86798994 0.15213717 0.67317413 0.19457566 0.71081822 0.90858517
  0.44532987 0.6258044  0.7938398  0.99910498]
 [0.8046132  0.52517616 0.00479276 0.91313595 0.81155257 0.93301225
  0.31850308 0.93276487 0.35575364 0.45560078]
 [0.44991784 0.30583921 0.70639816 0.49716658 0.94336065 0.27218664
  0.14034871 0.07071748 0.70620103 0.3915482 ]
 [0.2685971  0.05834154 0.95869109 0.77478558 0.10854053 0

In [19]:
# Generate a second random 10x10 matrix
random_matrix_B = np.random.rand(10, 10)
print("\nRandom 10x10 Matrix B:")
print(random_matrix_B)


Random 10x10 Matrix B:
[[0.81839336 0.38315099 0.93361056 0.33822034 0.38868174 0.92293088
  0.64051625 0.36148558 0.57142695 0.94679865]
 [0.83803787 0.63139845 0.39983108 0.81653248 0.55376572 0.84225501
  0.21156812 0.16686033 0.43171285 0.0048368 ]
 [0.4012116  0.9522052  0.50016393 0.26718603 0.33981193 0.12673036
  0.55476327 0.25328853 0.30657089 0.59959976]
 [0.06947937 0.32989775 0.84838136 0.81195197 0.09605766 0.57735159
  0.52524411 0.04587156 0.9042548  0.11226005]
 [0.7727518  0.11510149 0.67655888 0.69872599 0.57542176 0.00788183
  0.82686783 0.51096436 0.14693818 0.14539269]
 [0.53769151 0.81708173 0.45093095 0.57288393 0.26367714 0.10586351
  0.58124821 0.0383208  0.18986096 0.30772468]
 [0.66482937 0.73373558 0.41317304 0.05328999 0.82913479 0.79489797
  0.2204548  0.15360339 0.60065165 0.03216536]
 [0.81245045 0.03210449 0.63531399 0.51312414 0.70815037 0.86957271
  0.80370363 0.42373459 0.65282037 0.05582441]
 [0.85870714 0.61360966 0.94319419 0.78343318 0.27765791

In [20]:
# Matrix Addition
addition_result = random_matrix_A + random_matrix_B
print("\nA + B (Matrix Addition):")
print(addition_result)




A + B (Matrix Addition):
[[0.9831306  0.86224194 1.67561893 0.59307558 0.58153956 1.39071409
  0.74401292 0.41754774 0.95942415 1.51315317]
 [1.71068905 1.55240241 0.50046666 1.40010364 1.52914128 0.96975954
  0.84561722 1.0813654  1.38065439 0.59560037]
 [1.06650258 1.44184175 0.64722449 0.70574927 0.4404689  0.75346421
  0.63529491 0.75856352 0.3911822  1.01792178]
 [0.75251594 0.70219474 1.32113184 1.11214678 0.61983785 0.92652097
  1.21865583 0.57176679 1.08041672 0.40862984]
 [0.91544941 0.3318533  0.84525367 1.66530996 1.5600507  0.21304775
  1.42292044 0.51542306 0.59439402 0.58131407]
 [1.40568145 0.9692189  1.12410508 0.76745959 0.97449536 1.01444868
  1.02657809 0.6641252  0.98370076 1.30682966]
 [1.46944258 1.25891174 0.4179658  0.96642595 1.64068735 1.72791022
  0.53895787 1.08636826 0.95640529 0.48776614]
 [1.26236829 0.3379437  1.34171215 1.01029072 1.65151102 1.14175934
  0.94405235 0.49445207 1.3590214  0.44737261]
 [1.12730425 0.6719512  1.90188529 1.55821876 0.386198

In [21]:
# Matrix Subtraction
subtraction_result = random_matrix_A - random_matrix_B
print("\nA - B (Matrix Subtraction):")
print(subtraction_result)


A - B (Matrix Subtraction):
[[-0.65365611  0.09593996 -0.1916022  -0.0833651  -0.19582392 -0.45514768
  -0.53701959 -0.30542342 -0.18342975 -0.38044413]
 [ 0.03461331  0.28960551 -0.29919551 -0.23296133  0.42160983 -0.71475048
   0.42248098  0.74764473  0.51722869  0.58592677]
 [ 0.26407937 -0.46256865 -0.35310337  0.1713772  -0.23915496  0.50000349
  -0.47423163  0.25198646 -0.22195958 -0.18127774]
 [ 0.6135572   0.04239924 -0.37563087 -0.51175715  0.42772254 -0.22818221
   0.16816762  0.48002366 -0.72809288  0.18410975]
 [-0.63005418  0.10165031 -0.50786408  0.26785798  0.40920717  0.1972841
  -0.23081521 -0.50650567  0.30051767  0.29052869]
 [ 0.33029843 -0.66494457  0.22224318 -0.37830827  0.44714108  0.80272166
  -0.13591834  0.58748359  0.60397883  0.6913803 ]
 [ 0.13978383 -0.20855942 -0.40838028  0.85984596 -0.01758222  0.13811428
   0.09804828  0.77916149 -0.24489802  0.42343542]
 [-0.3625326   0.27373472  0.07108417 -0.01595756  0.23521028 -0.59738607
  -0.66335492 -0.353017

In [22]:
# Matrix Multiplication
multiplication_result = np.dot(random_matrix_A, random_matrix_B)
print("\nA * B (Matrix Multiplication):")
print(multiplication_result)


A * B (Matrix Multiplication):
[[2.07445696 2.14817498 1.97563644 1.73019702 1.45156551 1.47566126
  1.61272763 1.2949368  1.45407332 1.02368807]
 [4.7593914  2.7809497  4.45205955 3.69195775 3.36546855 3.85650674
  3.31171139 2.72698683 3.64252849 1.52950999]
 [2.27247808 1.70037014 2.23728253 1.88070097 1.57231395 2.20349331
  1.95617843 1.12990995 1.69790184 1.12930003]
 [2.90960488 2.16749131 2.71084473 1.98763893 2.24867994 2.4824932
  2.33361434 1.45245226 2.09449423 1.30777909]
 [2.37695157 1.87318882 2.75206937 2.35079882 1.85892558 1.80708589
  2.10224212 1.49955921 2.16264209 0.76256153]
 [4.3063737  3.27129226 4.04761368 2.98146847 3.01738314 3.02085453
  3.43059979 2.73794446 2.85144557 2.07640842]
 [3.86922131 2.50195546 3.97468183 3.42982695 2.73341815 3.28887282
  3.43758119 1.99021857 3.03933296 1.51668937]
 [2.83400148 2.2595476  3.02521674 2.50121377 1.87052659 1.67223598
  2.33267676 1.82067953 2.14386135 1.36250907]
 [1.82935728 2.02565078 2.36174842 1.79506952 1.3

In [23]:
# Transpose of random_matrix_A
transpose_result_A = random_matrix_A.T
print("\nTranspose of Matrix A:")
print(transpose_result_A)

# Transpose of random_matrix_B
transpose_result_B = random_matrix_B.T
print("\nTranspose of Matrix B:")
print(transpose_result_B)


Transpose of Matrix A:
[[0.16473724 0.87265118 0.66529098 0.68303657 0.14269761 0.86798994
  0.8046132  0.44991784 0.2685971  0.58210949]
 [0.47909095 0.92100396 0.48963655 0.37229699 0.21675181 0.15213717
  0.52517616 0.30583921 0.05834154 0.88621069]
 [0.74200837 0.10063558 0.14706056 0.47275049 0.1686948  0.67317413
  0.00479276 0.70639816 0.95869109 0.19508567]
 [0.25485524 0.58357116 0.43856323 0.30019481 0.96658397 0.19457566
  0.91313595 0.49716658 0.77478558 0.40977798]
 [0.19285782 0.97537555 0.10065697 0.5237802  0.98462893 0.71081822
  0.81155257 0.94336065 0.10854053 0.33156165]
 [0.4677832  0.12750453 0.62673385 0.34916938 0.20516593 0.90858517
  0.93301225 0.27218664 0.26096872 0.37624052]
 [0.10349667 0.6340491  0.08053164 0.69341173 0.59605261 0.44532987
  0.31850308 0.14034871 0.05347978 0.77153792]
 [0.05606216 0.91450507 0.50527499 0.52589523 0.0044587  0.6258044
  0.93276487 0.07071748 0.30485866 0.9609302 ]
 [0.3879972  0.94894154 0.08461131 0.17616192 0.44745584 

In [ ]:
# 1. Matrix Creation and Structure
# Question: Explain what a matrix is and provide an example of a 3×23 \times 23×2 matrix. Using NumPy, write code to create this matrix.

# matrix, a set of numbers arranged in rows and columns so as to form a rectangular array used for solving systems of linear equations and representing geometric transformations. (britannica)

# Creating a 3x23 matrix
matrix_a = np.random.randint(1, 10, size=(3, 23))

# Creating a 23x2 matrix
matrix_b = np.random.randint(1, 10, size=(23, 2))

# Multiplying the matrices
result_matrix = np.dot(matrix_a, matrix_b)

# Displaying the result
result_matrix


array([[692, 611],
       [581, 477],
       [605, 498]])

In [26]:
# 2. Basic Matrix Operations
# Question: Given two matrices A and B, describe the conditions necessary for performing matrix addition and matrix multiplication. 
# Write code to add and multiply two 5×5 matrices using NumPy.

# Conditions for Matrix Addition:
# They should have the same dimensions so matrices A and B should have the same number of rows and columns.

# Conditions for Matrix Multiplication:
# The number of columns in matrix A should be equal to the number of rows in matrix B.

# Creating two 5x5 matrices with random integers
matrix_a = np.random.randint(1, 10, size=(5, 5))
matrix_b = np.random.randint(1, 10, size=(5, 5))

# Performing matrix addition
addition_result = matrix_a + matrix_b

# Performing matrix multiplication
multiplication_result = np.dot(matrix_a, matrix_b)

# Displaying the results
addition_result, multiplication_result


(array([[11,  9,  9,  7,  3],
        [16,  5,  7,  4,  4],
        [12,  8, 11, 13, 14],
        [ 7,  9, 14, 12,  6],
        [ 2,  3, 12, 14, 13]]),
 array([[126,  64,  71, 132,  96],
        [ 64,  39,  52,  88,  68],
        [146,  70, 145, 190, 172],
        [141,  64,  95, 149, 118],
        [ 61,  35,  98, 112,  95]]))

In [28]:
# 3. Transpose of a Matrix
# Question: Explain the concept of matrix transposition. What effect does it have on a 3×2 matrix? Write code to create a 3×2 matrix and find its transpose.

#matrix transposition is where interchanging its rows into columns or columns into rows.

# Creating a 3x2 matrix
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# Finding the transpose of the matrix
transpose_matrix = np.transpose(matrix)

# Displaying the original and transposed matrices
matrix, transpose_matrix

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 3, 5],
        [2, 4, 6]]))

In [34]:
# 4. Working with Large Matrices
# Question: Create a random 5×5 matrix using NumPy. Compute the sum of all elements in the matrix, then find its transpose. Print both the sum and the transpose of the matrix.

# Creating a random 5x5 matrix
large_matrix = np.random.randint(1, 10, size=(5, 5))

# Computing the sum of all elements in the matrix
matrix_sum = np.sum(large_matrix)

# Finding the transpose of the matrix
matrix_transpose = np.transpose(large_matrix)

# Displaying the results
matrix_sum, matrix_transpose

(117,
 array([[7, 1, 6, 2, 3],
        [6, 6, 8, 2, 7],
        [5, 1, 5, 8, 6],
        [3, 6, 8, 7, 1],
        [7, 1, 3, 5, 3]]))

In [ ]:
# 5. Applying Matrix Operations in Context
# Question: Suppose you have two random 10×10 matrices D and E. Write code to (a) add the matrices, (b) subtract E from D, and (c) multiply D and E using matrix multiplication. Print each result and describe one possible application of each operation in computer science.

# Creating two random 10x10 matrices
matrix_d = np.random.randint(1, 10, size=(10, 10))
matrix_e = np.random.randint(1, 10, size=(10, 10))

# Performing (a) addition of matrices
addition_result = matrix_d + matrix_e

# Performing (b) subtraction of E from D
subtraction_result = matrix_d - matrix_e

# Performing (c) matrix multiplication of D and E
multiplication_result = np.dot(matrix_d, matrix_e)

# Displaying the results
addition_result, subtraction_result, multiplication_result

(array([[ 9,  3, 12,  9,  6,  3,  7, 17, 11, 10],
        [ 9,  6,  6,  3, 11,  6,  7,  3, 10,  9],
        [12,  5, 11, 14,  7,  9,  6, 12, 16, 11],
        [ 6, 12,  7, 14, 12, 14, 10, 13, 10, 17],
        [14, 10, 10, 12, 11,  4, 18, 12, 10,  5],
        [13,  8,  8, 16,  8,  8,  9, 15, 16,  3],
        [ 9, 12, 13, 16, 12,  6,  8, 13, 10, 15],
        [ 6, 10, 15,  9, 13,  5,  8, 11, 13, 11],
        [14,  6, 13,  8, 17, 11,  9,  4,  3,  9],
        [ 7, 11, 16, 15, 12, 13, 12,  6, 12, 12]]),
 array([[-1, -1,  0,  3,  2, -1, -1, -1, -1,  8],
        [-5,  4, -2,  1,  3,  0,  1, -1,  2,  1],
        [-4,  3, -1,  2, -3, -1, -4,  2,  0,  3],
        [-2,  0,  1,  2,  4,  2, -8, -1, -2,  1],
        [-4, -8, -8,  6,  7,  0,  0,  6,  2,  1],
        [-5, -4, -6,  2,  0,  4, -5,  3,  0, -1],
        [-7, -4, -3,  2,  4,  0,  4,  3, -8, -1],
        [ 4, -6, -3,  7, -5, -1,  2,  7, -3,  5],
        [-2, -4, -1, -2, -1,  1, -1,  2, -1,  5],
        [-1,  1,  2, -3, -6,  5,  2, -2, -6,  4]