In [1]:
import numpy as np

# Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Find the transpose
transpose_A = matrix_A.T

print("Matrix A:\n", matrix_A)
print("\nTranspose of Matrix A:\n", transpose_A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:


# Check if the matrix is symmetric
is_symmetric = (matrix_A == transpose_A).all()
print("\nIs Matrix A symmetric? ", is_symmetric)


Is Matrix A symmetric?  False


In [3]:
# Your solution here
random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T

# Check symmetry
is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)


Random Matrix:
 [[9 2 2 9]
 [9 2 1 4]
 [9 2 3 6]
 [9 2 3 9]]

Is the random matrix symmetric?  False


In [4]:
# Calculate the trace of matrix_A
trace_A = np.trace(matrix_A)
print("\nTrace of Matrix A:", trace_A)




Trace of Matrix A: 15


In [7]:
#Q3
matrix_B = np.array([[10, 20, 30],
                     [5, 15, 25],
                     [2, 4, 6]])

trace_B = np.trace(matrix_B)
print("\nTrace of Matrix B:", trace_B)


Trace of Matrix B: 31


In [9]:
#practice problem 2
identity_matrix = np.eye(5)
trace_identity = np.trace(identity_matrix)
print("\nTrace of 5x5 Identity Matrix:", trace_identity)


Trace of 5x5 Identity Matrix: 5.0


In [10]:
# Determinant using NumPy
det_A = np.linalg.det(matrix_A)
print("\nDeterminant of Matrix A:", det_A)



Determinant of Matrix A: 6.66133814775094e-16


In [11]:
# Determinant of a 2x2 matrix using the cofactor method
matrix_C = np.array([[4, 6], [3, 8]])
det_C = (matrix_C[0, 0] * matrix_C[1, 1]) - (matrix_C[0, 1] * matrix_C[1, 0])
print("Determinant of Matrix C:", det_C)



Determinant of Matrix C: 14


In [ ]:
#practice problem 3
matrix_D = np.array([[1, 2, 3],
                     [0, 4, 5],
                     [1, 0, 6]])

det_D = np.linalg.det(matrix_D)
print("Determinant of Matrix D:", det_D)

Determinant of Matrix D: 22.000000000000004


In [13]:
#practice problem 4
# Generate a random 3x3 matrix representing pixel intensities
pixel_matrix = np.random.randint(0, 256, (3, 3))

# Find the transpose of the pixel matrix
transpose_pixel_matrix = pixel_matrix.T

# Calculate the determinant of the pixel matrix
det_pixel_matrix = np.linalg.det(pixel_matrix)

print("Pixel Matrix:\n", pixel_matrix)
print("\nTranspose of Pixel Matrix:\n", transpose_pixel_matrix)
print("\nDeterminant of Pixel Matrix:", det_pixel_matrix)


Pixel Matrix:
 [[108  27 213]
 [193 153  84]
 [ 32 154  57]]

Transpose of Pixel Matrix:
 [[108 193  32]
 [ 27 153 154]
 [213  84  57]]

Determinant of Pixel Matrix: 4608266.999999991


In [18]:
#practice problem 5
# Create a symmetric 3x3 matrix
symmetric_matrix = np.array([[2, 3, 4],
                             [3, 5, 6],
                             [4, 6, 8]])

# Verify if the matrix is symmetric
is_symmetric_matrix = (symmetric_matrix == symmetric_matrix.T).all()

print("Symmetric Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric? ", is_symmetric_matrix)

Symmetric Matrix:
 [[2 3 4]
 [3 5 6]
 [4 6 8]]

Is the matrix symmetric?  True
