In [3]:
import numpy as np

# Define a 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])

# Check if the matrix is invertible
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("Inverse of A:")
    print(A_inv)
else:
    print("Matrix A is not invertible.")

Determinant of A: 10.000000000000002
Inverse of A:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [4]:
# Coefficient matrix
A = np.array([[4, 7],
              [2, 6]])

# Constant vector
b = np.array([10, 8])

# Solve for x using matrix inverse
if np.linalg.det(A) != 0:
    x = np.linalg.inv(A).dot(b)
    print("Solution for [x, y]:")
    print(x)
else:
    print("Matrix A is not invertible, no unique solution.")



Solution for [x, y]:
[0.4 1.2]


In [ ]:
#problem 1

# Define the new 2x2 matrix
a = np.array([[3, 4],
              [2, 5]])

# Check if the matrix is invertible
det_a = np.linalg.det(a)
print(f"Determinant of a: {det_a}")

if det_a != 0:
    # Calculate the inverse
    a_inv = np.linalg.inv(a)
    print("Inverse of a:")
    print(a_inv)
else:
    print("Matrix a is not invertible.")

Determinant of a: 7.000000000000001
Inverse of a:
[[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


In [ ]:
#problem 2

# Coefficient matrix
A_new = np.array([[2, 3],
                  [4, -1]])

# Constant vector
b_new = np.array([7, 5])

# Solve for x using matrix inverse
if np.linalg.det(A_new) != 0:
    x_new = np.linalg.inv(A_new).dot(b_new)
    print("Solution for [x, y]:")
    print(x_new)
else:
    print("Matrix A_new is not invertible, no unique solution.")

Solution for [x, y]:
[1.57142857 1.28571429]


In [ ]:
#problem 3

# Define the 3x3 matrix
A_3x3 = np.array([[1, 2, 3],
                  [0, 1, 4],
                  [5, 6, 0]])

# Check if the matrix is invertible
det_A_3x3 = np.linalg.det(A_3x3)
print(f"Determinant of A_3x3: {det_A_3x3}")

if det_A_3x3 != 0:
    # Calculate the inverse
    A_3x3_inv = np.linalg.inv(A_3x3)
    print("Inverse of A_3x3:")
    print(A_3x3_inv)
else:
    print("Matrix A_3x3 is not invertible.")

Determinant of A_3x3: 0.9999999999999964
Inverse of A_3x3:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [ ]:
#problem 4
# Coefficient matrix
A_system = np.array([[1, 1, 1],
                     [2, 5, 1],
                     [2, 3, 8]])

# Constant vector
B_system = np.array([6, -4, 9])

# Check if the matrix is invertible
det_A_system = np.linalg.det(A_system)
print(f"Determinant of A_system: {det_A_system}")

if det_A_system != 0:
    # Calculate the inverse
    A_system_inv = np.linalg.inv(A_system)
    # Solve for X using matrix inverse
    X_solution = A_system_inv.dot(B_system)
    print("Solution for [x, y, z]:")
    print(X_solution)
else:
    print("Matrix A_system is not invertible, no unique solution.")

Determinant of A_system: 18.999999999999996
Solution for [x, y, z]:
[10.84210526 -5.21052632  0.36842105]


In [ ]:
#problem 5
# Define the coefficient matrix A and the constant vector b
A_new_system = np.array([[4, -1, 0],
                         [3, 5, 2],
                         [-2, 4, 1]])

b_new_system = np.array([5, 6, 2])

# Check if the matrix is invertible
det_A_new_system = np.linalg.det(A_new_system)
print(f"Determinant of A_new_system: {det_A_new_system}")

if det_A_new_system != 0:
    # Calculate the inverse
    A_new_system_inv = np.linalg.inv(A_new_system)
    # Solve for x using matrix inverse
    x_new_system = A_new_system_inv.dot(b_new_system)
    print("Solution for [x, y, z]:")
    print(x_new_system)
else:
    print("Matrix A_new_system is not invertible, no unique solution.")

Determinant of A_new_system: -5.000000000000002
Solution for [x, y, z]:
[  2.6   5.4 -14.4]


In [ ]:
#bonus challenge
def check_invertible(matrix):
    # Calculate the determinant of the matrix
    determinant = np.linalg.det(matrix)
    
    # Check if the determinant is zero
    if determinant == 0:
        print("The matrix is not invertible.")
        return None
    else:
        # Calculate the inverse of the matrix
        inverse_matrix = np.linalg.inv(matrix)
        return inverse_matrix

# Example usage:
matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]])

inverse = check_invertible(matrix)
if inverse is not None:
    print("Inverse of the matrix:")
    print(inverse)

Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
